DELETE http://localhost:3003/api/blogs/61c33776b640c6b257b5b608
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2MWMzMzcxNDA5Mjk0ZjE0NTFhYjUyZTciLCJpYXQiOjE2NDAxODM3ODIsImV4cCI6MTY0MDE4NzM4Mn0.4WcznAGtz7v614_ktxOr0G5rwhgj0Y1X_fYPs4sLx2E